---
name: Build and deploy

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to build and deploy"
        required: true
        default: "master"
        type: string

env:
  TRUNK_VERSION: "0.21.4"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: rustup add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: Prep the Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        run: cargo install --locked trunk@${TRUNK_VERSION}
      -
        name: Build the app
        run: trunk build --release
      # -
      #   name: Build and push the image
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: turboladen/putitinthepizza:latest
      - name: Build the image
        run: docker build -t turboladen/putitinthepizza:latest .
      - name: Push the image
        run: docker push turboladen/putitinthepizza:latest
