---
name: Build and deploy

on:
  push:
    # Doing all branches until I get it working.
    # branches:
      # - "master"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Install trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/${VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      -
        name: Build the app
        run: trunk build --release
      -
        name: Build and push the image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: turboladen/putitinthepizza:latest

