---
name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: rustup add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: Prep the Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "v0.21.4"

      - name: Build the app
        run: trunk build
