---
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy"
        required: true
        default: "master"
        type: string

env:
  TRUNK_VERSION: "0.21.4"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as
# we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: rustup add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Prep the Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install trunk
        run: cargo install --locked trunk@${TRUNK_VERSION}
      - name: Build (trunk)
        run: trunk build --release

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload output from `trunk build`
          path: 'dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
